[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nipoppy"
authors = [{ name = "nikhil153" }]
version = "0.1.0"


dependencies = [
    "pandas",
    "numpy",
    "joblib",
    "pydicom",
    "nibabel",
    "pybids",
    "requests",
]

[project.optional-dependencies]
test = [
    "nipoppy[bidscoin]",
    "pytest"
]

# alias in case of typo
tests = ["nipoppy[test]"]

bidscoin = ["bidscoin@git+https://github.com/Donders-Institute/bidscoin.git"]

[tool.hatch.build.targets.wheel]
packages = ["nipoppy"]

[tool.hatch.build]
include = [
    "nipoppy/workflow/proc_pipe/tractoflow/tractoflow",
]
[tool.hatch.metadata]
allow-direct-references = true

[tool.codespell]
skip = '.git,.github,*.pdf,*.svg,pyproject.toml,*.ipynb,*.html,ppmi_imaging_descriptions.json'
ignore-words-list = 'te,ines'

[tool.pytest.ini_options]
addopts = "-ra -q -vv "
testpaths = ["tests/"]